### ISSUE TITLE
Bug in component system with molecular_weight

### ISSUE THREAD

**Issue by daklauss** [fau-advanced-separations/CADET-Process#164]
In `CADETProcess.processModel.componentSystem` on line 134 the property for molecular weight of a component ist set with.
```
    @property
    def molecular_weight(self):
        """list of float or None: The molecular weights of the subspecies."""
        return [spec.molecular_weight for spec in self.molecular_weight]
```
so calling `molecular_weight` leads to an inifinite recursion.

Line 137 should be `[spec.molecular_weight for spec in self.species]`

Example:
```
from CADETProcess.processModel import ComponentSystem

componentsystem = ComponentSystem(2)

componentsystem.molecular_weights
```
leads to 

```
Traceback (most recent call last):
  File "c:\Users\klauss\Documents\Arbeitsprojekte\ModSim\Bachelorarbeit\smalltest.py", line 5, in <module>     
    componentsystem.molecular_weights
  File "C:\Users\klauss\AppData\Local\miniconda3\envs\processnew\Lib\site-packages\CADETProcess\processModel\componentSystem.py", line 378, in molecular_weights
    molecular_weights += comp.molecular_weight
                         ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\klauss\AppData\Local\miniconda3\envs\processnew\Lib\site-packages\CADETProcess\processModel\componentSystem.py", line 137, in molecular_weight
    return [spec.molecular_weight for spec in self.molecular_weight]
                                              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\klauss\AppData\Local\miniconda3\envs\processnew\Lib\site-packages\CADETProcess\processModel\componentSystem.py", line 137, in molecular_weight
    return [spec.molecular_weight for spec in self.molecular_weight]
                                              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\klauss\AppData\Local\miniconda3\envs\processnew\Lib\site-packages\CADETProcess\processModel\componentSystem.py", line 137, in molecular_weight
    return [spec.molecular_weight for spec in self.molecular_weight]
                                              ^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 995 more times]
RecursionError: maximum recursion depth exceeded
```

Maybe consider using aggregate class for property generation.

**Comment by schmoelder** [comment]
But you did fix it for CADET-Python-Simulator, right?

**Comment by schmoelder** [comment]
Yes, please make sure to also fix issues upstream.
