### ISSUE TITLE
COBYLA does not respect bounds

### ISSUE THREAD

**Issue by schmoelder** [fau-advanced-separations/CADET-Process#47]
Since `scipy==1.11`, `COBYLA` should support bound constraints, however, a test problems crashes because it exceeds bounds (@flo-schu).

First step might be to reproduce the problems used by scipy's tests and see if they work in CADET-Process:
- https://github.com/scipy/scipy/blob/cfe80116aaa145061246b8aec0e98248fbefb835/scipy/optimize/tests/test_cobyla.py#L130
- https://github.com/scipy/scipy/blob/cfe80116aaa145061246b8aec0e98248fbefb835/scipy/optimize/tests/test_optimize.py#L1579

**Comment by flo-schu** [comment]
Unbounded problems work fine for COBYLA

```py
class COBYLATestProblem1(TestProblem):
    def __init__(self, *args, **kwargs):
        super().__init__(name="cobyla_test_problem", *args, **kwargs)
        # when no bound is set, (+/-) math.inf is assumed
        self.add_variable("var_0")
        self.add_variable("var_1")

        self.add_objective(self._objective_function)

    def _objective_function(self, x):
        return np.sum(x**2)
    
    @property
    def optimal_solution(self):
        x_true = np.array([[0.0, 0.0]])
        return x_true

    @property
    def x0(self):
        return [1, 2]

    def test_if_solved(self, results, decimal=7):
        x_true = self.optimal_solution
        x = results.x_untransformed
        np.testing.assert_almost_equal(x_true, x, decimal=decimal)


settings.working_directory = "work"

problem = COBYLATestProblem1()
optimizer = COBYLA()
optimizer.optimize(
    optimization_problem=problem,
    x0=problem.x0,
    save_results=False,
    results_directory="work/cobyla/"
)
problem.test_if_solved(optimizer.results, decimal=4)
```

This problem works without raising any errors

**Comment by flo-schu** [comment]
Bounded problems raise an error in CADET process. If I remember correctly, this could have to do with the `keep_feasible=True` flag which may not be enforced any longer in scipy. Maybe this raised a deprecation warning in previous versions and does not any longer? In any case, `COBYLA` handles bounds as transforms in Scipy 1.11, I think this can conflict with CADET-Process.


```py
class COBYLATestProblem2(TestProblem):
    def __init__(self, *args, **kwargs):
        super().__init__(name="cobyla_test_problem", *args, **kwargs)
        # when no bound is set, (+/-) math.inf is assumed
        self.add_variable("var_0", lb=-1, ub=-0.5)
        self.add_variable("var_1", ub=-0.5)
        self.add_variable("var_2", lb=1)
        self.add_variable("var_3")
        self.add_variable("var_4", lb=-0.5001, ub=-0.4999)

        self.add_objective(self._objective_function)

    def _objective_function(self, x):
        return np.sum(x**2)
    
    @property
    def optimal_solution(self):
        x_true = np.array([[-0.5, -0.5, 1, 0, -0.5]])
        return x_true

    @property
    def x0(self):
        return [1, 2, 3, 4, 5]
    
    def test_if_solved(self, results, decimal=7):
        x_true = self.optimal_solution
        x = results.x_untransformed
        np.testing.assert_almost_equal(x_true, x, decimal=decimal)

problem = COBYLATestProblem2()
optimizer = COBYLA()
optimizer.optimize(
    optimization_problem=problem,
    x0=problem.x0,
    save_results=False,
    results_directory="work/cobyla/"
)
problem.test_if_solved(optimizer.results, decimal=4)
```


## Traceback

```
Traceback (most recent call last):
  File "<string>", line 33, in <module>
  File "/home/flo-schu/projects/CADET-Process/CADETProcess/optimization/optimizer.py", line 227, in optimize
    self.run(self.optimization_problem, x0, *args, **kwargs)
  File "/home/flo-schu/projects/CADET-Process/CADETProcess/optimization/scipyAdapter.py", line 120, in run
    scipy_results = optimize.minimize(
  File "/home/flo-schu/miniconda3/envs/cadet-process/lib/python3.10/site-packages/scipy/optimize/_minimize.py", line 716, in minimize
    res = _minimize_cobyla(fun, x0, args, constraints, callback=callback,
  File "/home/flo-schu/miniconda3/envs/cadet-process/lib/python3.10/site-packages/scipy/optimize/_cobyla_py.py", line 34, in wrapper
    return func(*args, **kwargs)
  File "/home/flo-schu/miniconda3/envs/cadet-process/lib/python3.10/site-packages/scipy/optimize/_cobyla_py.py", line 285, in _minimize_cobyla
    xopt, info = cobyla.minimize(calcfc, m=m, x=np.copy(x0), rhobeg=rhobeg,
  File "/home/flo-schu/miniconda3/envs/cadet-process/lib/python3.10/site-packages/scipy/optimize/_cobyla_py.py", line 273, in calcfc
    f = fun(np.copy(x), *args)
  File "/home/flo-schu/projects/CADET-Process/CADETProcess/optimization/scipyAdapter.py", line 81, in objective_function
    return optimization_problem.evaluate_objectives(x)[0]
  File "/home/flo-schu/projects/CADET-Process/CADETProcess/optimization/optimizationProblem.py", line 131, in wrapper
    return func(self, x, *args, **kwargs)
  File "/home/flo-schu/projects/CADET-Process/CADETProcess/optimization/optimizationProblem.py", line 983, in evaluate_objectives
    f = self._evaluate_individual(self.objectives, x, force=force)
  File "/home/flo-schu/projects/CADET-Process/CADETProcess/optimization/optimizationProblem.py", line 603, in _evaluate_individual
    value = self._evaluate(x, eval_fun, force)
  File "/home/flo-schu/projects/CADET-Process/CADETProcess/optimization/optimizationProblem.py", line 131, in wrapper
    return func(self, x, *args, **kwargs)
  File "/home/flo-schu/projects/CADET-Process/CADETProcess/optimization/optimizationProblem.py", line 696, in _evaluate
    evaluation_objects = self.set_variables(x, func.evaluation_objects)
  File "/home/flo-schu/projects/CADET-Process/CADETProcess/optimization/optimizationProblem.py", line 131, in wrapper
    return func(self, x, *args, **kwargs)
  File "/home/flo-schu/projects/CADET-Process/CADETProcess/optimization/optimizationProblem.py", line 511, in set_variables
    values = self.get_dependent_values(x)
  File "/home/flo-schu/projects/CADET-Process/CADETProcess/optimization/optimizationProblem.py", line 131, in wrapper
    return func(self, x, *args, **kwargs)
  File "/home/flo-schu/projects/CADET-Process/CADETProcess/optimization/optimizationProblem.py", line 442, in get_dependent_values
    variable.value = float(value)
  File "/home/flo-schu/projects/CADET-Process/CADETProcess/optimization/optimizationProblem.py", line 2907, in value
    raise ValueError("Exceeds upper bound")
ValueError: Exceeds upper bound
```

**Comment by flo-schu** [comment]
A possible solution could be to implement an unbounded transform such as standard scaling transform and use constraints instead of bounds to limit the parameter space

**Comment by schmoelder** [comment]
In the context of #103, I wanted to try and also fix this issue. For this purpose, I wanted to take `COBYLATestProblem2`, however, I noticed that already the initial value `x0` that is provided in the class violates the bound constraints. Do you have another quick MRE that I could use?

**Comment by flo-schu** [comment]
I think you could use any of the single objective test optimization problem fixtures. They don't provide init values by default, but you could just use something close to the init values.

**Comment by zaikunzhang** [comment]
See 

https://github.com/libprima/prima/issues/42

**Comment by flo-schu** [comment]
> See
> 
> [libprima/prima#42](https://github.com/libprima/prima/issues/42)

Thank you for this input @zaikunzhang. That is a very useful piece of information!

**Comment by schmoelder** [comment]
COBYLA bounds support was added in scipy 1.11. The adapter already passes bounds via scipy.optimize.Bounds and sets supports_bounds=True. All COBYLA slow tests pass without exclusions. Closing as resolved.
