### ISSUE TITLE
Test (test_optimization_integration.TestFitColumnParameters) sometimes breaks on GitHub CI with sqlite error

### ISSUE THREAD

**Issue by ronald-jaepel** [fau-advanced-separations/CADET-Process#85]
Sometimes, mostly when running multiple CI pipelines at the same time, the test (test_optimization_integration.TestFitColumnParameters) breaks with the error 

```
ERROR: test_optimization (test_optimization_integration.TestFitColumnParameters)
----------------------------------------------------------------------
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/runner/miniconda3/envs/cadet-process/lib/python3.10/site-packages/joblib/externals/loky/process_executor.py", line 426, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "/home/runner/miniconda3/envs/cadet-process/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "/home/runner/work/CADET-Process/CADET-Process/examples/characterize_chromatographic_system/column_transport_parameters.py", line 170, in <module>
    optimization_problem = OptimizationProblem('bed_porosity_axial_dispersion')
  File "/home/runner/work/CADET-Process/CADET-Process/CADETProcess/dataStructure/dataStructure.py", line 482, in wrapper
    func(self, *args, **kwargs)
  File "/home/runner/work/CADET-Process/CADET-Process/CADETProcess/optimization/optimizationProblem.py", line 117, in __init__
    self.setup_cache()
  File "/home/runner/work/CADET-Process/CADET-Process/CADETProcess/optimization/optimizationProblem.py", line 2635, in setup_cache
    self.cache = ResultsCache(self.use_diskcache, self.cache_directory)
  File "/home/runner/work/CADET-Process/CADET-Process/CADETProcess/optimization/cache.py", line 45, in __init__
    self.init_cache()
  File "/home/runner/work/CADET-Process/CADET-Process/CADETProcess/optimization/cache.py", line 60, in init_cache
    self.cache = Cache(
  File "/home/runner/miniconda3/envs/cadet-process/lib/python3.10/site-packages/diskcache/core.py", line 478, in __init__
    self.reset(key, value, update=False)
  File "/home/runner/miniconda3/envs/cadet-process/lib/python3.10/site-packages/diskcache/core.py", line 2438, in reset
    sql('PRAGMA %s = %s' % (pragma, value)).fetchall()
sqlite3.OperationalError: attempt to write a readonly database
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/work/CADET-Process/CADET-Process/tests/test_optimization_integration.py", line 146, in test_optimization
    results = self.optimizer.optimize(
  File "/home/runner/work/CADET-Process/CADET-Process/CADETProcess/optimization/optimizer.py", line 254, in optimize
    self.run(self.optimization_problem, x0, *args, **kwargs)
  File "/home/runner/work/CADET-Process/CADET-Process/CADETProcess/optimization/pymooAdapter.py", line 160, in run
    algorithm.evaluator.eval(problem, pop)
  File "/home/runner/miniconda3/envs/cadet-process/lib/python3.10/site-packages/pymoo/core/evaluator.py", line 69, in eval
    self._eval(problem, pop[I], evaluate_values_of, **kwargs)
  File "/home/runner/miniconda3/envs/cadet-process/lib/python3.10/site-packages/pymoo/core/evaluator.py", line 90, in _eval
    out = problem.evaluate(X, return_values_of=evaluate_values_of, return_as_dictionary=True, **kwargs)
  File "/home/runner/miniconda3/envs/cadet-process/lib/python3.10/site-packages/pymoo/core/problem.py", line 257, in evaluate
    _out = self.do(X, return_values_of, *args, **kwargs)
  File "/home/runner/miniconda3/envs/cadet-process/lib/python3.10/site-packages/pymoo/core/problem.py", line 299, in do
    self._evaluate_vectorized(X, out, *args, **kwargs)
  File "/home/runner/miniconda3/envs/cadet-process/lib/python3.10/site-packages/pymoo/core/problem.py", line 307, in _evaluate_vectorized
    self._evaluate(X, out, *args, **kwargs)
  File "/home/runner/work/CADET-Process/CADET-Process/CADETProcess/optimization/pymooAdapter.py", line 243, in _evaluate
    F = opt.evaluate_objectives_population(
  File "/home/runner/work/CADET-Process/CADET-Process/CADETProcess/optimization/optimizationProblem.py", line 138, in wrapper
    return func(self, x, *args, **kwargs)
  File "/home/runner/work/CADET-Process/CADET-Process/CADETProcess/optimization/optimizationProblem.py", line 159, in wrapper
    return func(self, population, *args, **kwargs)
  File "/home/runner/work/CADET-Process/CADET-Process/CADETProcess/optimization/optimizationProblem.py", line 1065, in evaluate_objectives_population
    results = self._evaluate_population(
  File "/home/runner/work/CADET-Process/CADET-Process/CADETProcess/optimization/optimizationProblem.py", line 713, in _evaluate_population
    results = parallelization_backend.evaluate(eval_fun_wrapper, population)
  File "/home/runner/work/CADET-Process/CADET-Process/CADETProcess/optimization/parallelizationBackend.py", line 148, in evaluate
    results = backend(delayed(function)(x) for x in population)
  File "/home/runner/miniconda3/envs/cadet-process/lib/python3.10/site-packages/joblib/parallel.py", line 1952, in __call__
    return output if self.return_generator else list(output)
  File "/home/runner/miniconda3/envs/cadet-process/lib/python3.10/site-packages/joblib/parallel.py", line 1595, in _get_outputs
    yield from self._retrieve()
  File "/home/runner/miniconda3/envs/cadet-process/lib/python3.10/site-packages/joblib/parallel.py", line 1699, in _retrieve
    self._raise_error_fast()
  File "/home/runner/miniconda3/envs/cadet-process/lib/python3.10/site-packages/joblib/parallel.py", line 1734, in _raise_error_fast
    error_job.get_result(self.timeout)
  File "/home/runner/miniconda3/envs/cadet-process/lib/python3.10/site-packages/joblib/parallel.py", line 736, in get_result
    return self._return_or_raise()
  File "/home/runner/miniconda3/envs/cadet-process/lib/python3.10/site-packages/joblib/parallel.py", line 754, in _return_or_raise
    raise self._result
joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.
```

**Comment by schmoelder** [comment]
Resolved by the parameter space refactor (#388, v0.13.0): diskcache was replaced by pipefunc's built-in cache backends, removing the sqlite dependency entirely.
